### ISSUE TITLE
macOS: Cannot find libusb on M1 Macs?

### ISSUE THREAD

**Issue by jseaber** [jdslabs/xmos_dfu#2]
Running `make -f Makefile.OSX all` on an M1 may fail to find `libusb`. This may be due to absence of `libusb`, or the location may differ on the M1 architecture. 

Need to confirm on an M1 machine.

![image](https://user-images.githubusercontent.com/9965388/154401950-bd1132be-ba6b-4baf-91c7-df550282113e.png)

**Comment by evancalkins** [comment]
M1 Macs can update line 2 in the Makefile.OSX to look this:

`g++ -g -o xmosdfu xmosdfu.cpp -I. -IOSX /opt/homebrew/Cellar/libusb/1.0.25/lib/libusb-1.0.0.dylib`

**Comment by jseaber** [comment]
Thanks, @evancalkins. This improvement is staged on branch https://github.com/jdslabs/xmos_dfu/tree/fix/m1

New make commands will be:

`make -f Makefile mac`
`make -f Makefile mac-m1`
`make -f Makefile linux`

I'll test all targets and we'll update instructions as soon as our M1 machine arrives.

**Comment by jseaber** [comment]
Fix has been merged into `main`, noting the following on a new M1 machine:

XCode Command Line Tools must be installed from the App Store. The usual command `xcode-select --install` did not work on the first try?

If this error appears, Homebrew and/or liibusb are not installed correctly:

```
clang: error: no such file or directory: '/opt/homebrew/Cellar/libusb/1.0.25/lib/libusb-1.0.0.dylib'
```
